# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.

#Что нужно сделать:
#  - Настроить сервисы для:
#      - PostgreSQL (или MySQL) с начальной базой.
#      - Приложения Spring Boot (если нужно).
#  - Открыть нужные порты (например, 5432, 8080).
#  - Настроить volume для хранения данных БД.

#version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank_container
    ports:
      - "7777:7777"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/card_db
      SPRING_DATASOURCE_USERNAME: card_user
      SPRING_DATASOURCE_PASSWORD: card_psw

  db:
    image: postgres:16
    container_name: psq_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: card_user
      POSTGRES_PASSWORD: card_psw
      POSTGRES_DB: card_app
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
